---
title: "Küresel Savunma Harcamaları"
author: 
  - Tibethan Furkan Yalçın[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 19080764, [Github Repo](https://github.com/tfrkny/aras-navson.git)

 
# Giriş
Yüzyıllardır süre gelen dünya tarihinde ilk şehir devletlerinden günümüz modern ulus devletlerine kadar gelişen süreçte dünya sayısız savaş tecrübesi edinmiştir. Bu savaşalar kimi
zaman iki aktör arasında yaşanırken kimi zamanda ikiden fazla aktörün de taraf olduğu bölgesel nitelikte savaşlarda meydana gelmiştir. En son yaklaşık 100 yıl önce dünya arka arkaya
2 küresel düzeyde savaşa sahne olmuştur. Ve halen günümüzde dahil dünyanın birçok yerinde
fiili savaş devam etmektedir. Tüm bu sonuçlar neticesiyle dünya üzerindeki birçok devlet gelirlerinin büyük bir kısmını savunma harcamalarına ve savunma sanayi ürünlerinin ithalatı
için kullanılmaktadır. Bu çalışmanın konusuda ülkelerin savunma harcamalarına ne kadar
önem verdiklerini irdelemek, gider kalemlerinin büyük bir çoğunluğunun bu harcamaları oluşturduğunu aktarmaya çalışmaktır. Çalışmada kullanılacak veriler ; Stockholm Uluslararası
Barış Araştırmaları Enstitüsü (SIPRI) raporlarından baz alınarak oluşturulmuştur.


## Çalışmanın Amacı
Bu çalışmanın amacı küresel düzeyde yapılan savunma harcamalarının ülkelerin ne kadar
önem verdiğini anlamak, uluslararası ticaretin büyük bir kısmının savunma sanayi ürünlerinden meydana geldiğinin üzerinde durmak ve bu ticaretin ülkelerin dış politikasının ve ekonomi politiği kavramının üzerinde nasıl bir etki bıraktığını analiz etmektir.

## Literatür 
Küreselleşme kavramının ülkelerin dış politika kararlarındaki etkisi o ülkenin güvenlik algısı
ve buna bağlı olarak savunma harcamaları üzerindeki etkisidir.Araştırmacılara göre küreselleşen dünya uluslararası ticarette bir takım avantajlar sağlamış akabinde bu avantajlar
bir takım fırsat maliyetleri oluşturmuş ve refah etkisini arttırmıştır. Bu nedenle ülkeler arası çatışma eğilimi azalacak ve savunma harcamalarının gider kalemleri içindeki payıda azalacaktır. Fakat elimizdeki veriler bunun tam tersi sonuç doğurduğunu göstermektedir. Çünkü küreselleşme kavramını farklı değerlendiren ulus devletleri güvenlik algılarının olumsuz yönde etkilenmesine bağlı olarak savunma harcamalarında artış görüldüğünü anlaşılmaktadır.@cengizkuresellecsme

Savunma harcamaları devletlerin siyasi varlığının ülke sınırları içerisinde veya dışarısında
herhangi bir güvenlik zafiyetiyle karşılaşılması durumlarına hazırlık olarak milli gelirden
yapılan harcamalardır.@csicsman2017kuresellecsme

Günümüzde siyasi, coğrafi ve kültürel sınırların kısmende olsa ortadan kalkmasıyla sermayenin dolaşımdaki hızının artmasıyla birlikte ülkeler arasındaki bağlantılar ve ilişkiler çeşitlik kazanmıştır.Küreselleşme savunma harcamalarını diğer sosyal harcamalara göre daha fazla teşvik etmektedir. Buna bağlı olarakda küreselleşme çatışma ortamına, eşitsizliğe, huzursuzluğa neden olduğu düşünülmektedir.@torusdaugfinansa

Savunma harcamaları; ülkeye karşı saldırılarda caydırıcı bir güç olmasının yanında, olası bir saldırı ile karşı karşıya kaldığında bu saldırıya karşı konularak engellemesini sağlamak için yapılan harcamalardır. Savunma harcamalarının bu iki yönü düşünüldüğünde bu harcamaların hem barış hem de savaş dönemlerinde gerçekleştirilmesi gerektiğini ortaya koymaktadır.Saldırı veya savaş öncesi gerçekleştirilen savunma harcamaları devletin gücünü gösterir. Saldırı anında ise tehlikeye karşı konulması açısından önem arz etmektedir. Bu nedenle ülkeler genellikle gerginlik dönemlerinde bu harcamalarının düzeyini arttırırlar. Savunma harcamalarını belirleyen birçok faktör bulunmaktadır. Ekonomik faktörler (milli gelir, bütçe) ve ekonomik olmayan faktörler (coğrafi konum, jeopolitik konum ve siyasi rejim) olarak iki ana başlık altında düşünülebilir.Yolcu vd. (2020)


\newpage
# Kaynakça {#references}
<div id="refs"></div>
https://www.sipri.org/databases/milex

https://dergipark.org.tr/en/pub/sayistay/issue/61573/919324

https://acikbilim.yok.gov.tr/handle/20.500.12812/690165

https://dergipark.org.tr/en/pub/asead/issue/41905/505227

https://dergipark.org.tr/en/pub/kmusekad/issue/67623/995650

https://dergipark.org.tr/en/download/article-file/328033

https://acikerisim.sakarya.edu.tr/handle/20.500.12619/92882
